apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.userService.name }}
            port:
              number: 80
      - path: /salles
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.salleService.name }}
            port:
              number: 80
      - path: /reservations
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.reservationService.name }}
            port:
              number: 80