{{- define "common.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .port }}
  type: ClusterIP
{{- end -}}

{{- if .Values.userService -}}
---
{{- include "common.service" .Values.userService | nindent 0 }}
{{- end }}

{{- if .Values.salleService -}}
---
{{- include "common.service" .Values.salleService | nindent 0 }}
{{- end }}

{{- if .Values.reservationService -}}
---
{{- include "common.service" .Values.reservationService | nindent 0 }}
{{- end }}