apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENVIRONMENT: production
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
  JAEGER_AGENT_HOST: "jaeger-agent"
  JAEGER_AGENT_PORT: "6831"